/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kinomaniak_mgmt;
import kinomaniak_objs.*;

/**
 *
 * @author qbass
 */
public class MainFrame extends javax.swing.JFrame {
     MovieDBMgmt2 mgmt;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        pOptions.setVisible(false);
        pMain.setVisible(true);
        bLoad.setVisible(true);
        bSave.setVisible(false);
        pAddMov.setVisible(false);
        pListMov.setVisible(false);
        bReturn.setVisible(false);
        this.mgmt = new MovieDBMgmt2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        pAddCRoom = new javax.swing.JPanel();
        lCRoomHello = new javax.swing.JLabel();
        lCRoomID = new javax.swing.JLabel();
        pMain = new javax.swing.JPanel();
        bLoad = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        pOptions = new javax.swing.JPanel();
        bAddMov = new javax.swing.JButton();
        bAddCRoom = new javax.swing.JButton();
        bAddShow = new javax.swing.JButton();
        bListMov = new javax.swing.JButton();
        bListShow = new javax.swing.JButton();
        bListCRoom = new javax.swing.JButton();
        bDelMov = new javax.swing.JButton();
        bDelCRoom = new javax.swing.JButton();
        bDelShow = new javax.swing.JButton();
        bAddUser = new javax.swing.JButton();
        bListUser = new javax.swing.JButton();
        bDelUser = new javax.swing.JButton();
        bListRes = new javax.swing.JButton();
        pListMov = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liMovieList = new javax.swing.JList();
        bDelMovie = new javax.swing.JButton();
        bShowMore = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tMovieMore = new javax.swing.JTextArea();
        pAddMov = new javax.swing.JPanel();
        eMovieName = new javax.swing.JTextField();
        lMovieName = new javax.swing.JLabel();
        lMovieGenre = new javax.swing.JLabel();
        lMovieRating = new javax.swing.JLabel();
        lMovieDesc = new javax.swing.JLabel();
        eMovieGenre = new javax.swing.JTextField();
        eMovieRating = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMovieDesc = new javax.swing.JTextArea();
        bAddMovOK = new javax.swing.JButton();
        bReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lCRoomHello.setText("Adding CRoom with 10x10 seats...");

        lCRoomID.setText("Last CRoom ID: ");

        javax.swing.GroupLayout pAddCRoomLayout = new javax.swing.GroupLayout(pAddCRoom);
        pAddCRoom.setLayout(pAddCRoomLayout);
        pAddCRoomLayout.setHorizontalGroup(
            pAddCRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddCRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAddCRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCRoomHello)
                    .addComponent(lCRoomID))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        pAddCRoomLayout.setVerticalGroup(
            pAddCRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddCRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCRoomHello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lCRoomID)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pAddCRoom.setBounds(0, 0, 420, 260);
        jLayeredPane1.add(pAddCRoom, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bLoad.setText("LOAD");
        bLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoadActionPerformed(evt);
            }
        });

        bSave.setText("SAVE");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bAddMov.setText("Add Movie");
        bAddMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddMovActionPerformed(evt);
            }
        });

        bAddCRoom.setText("Add CRoom");

        bAddShow.setText("Add Show");

        bListMov.setText("List Movies");
        bListMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListMovActionPerformed(evt);
            }
        });

        bListShow.setText("List Shows");

        bListCRoom.setText("List CRooms");

        bDelMov.setText("Del Movie");

        bDelCRoom.setText("Del CRoom");

        bDelShow.setText("Del Show");

        bAddUser.setText("Add User");

        bListUser.setText("List Users");

        bDelUser.setText("Del User");

        bListRes.setText("List Res");

        javax.swing.GroupLayout pOptionsLayout = new javax.swing.GroupLayout(pOptions);
        pOptions.setLayout(pOptionsLayout);
        pOptionsLayout.setHorizontalGroup(
            pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAddMov)
                    .addComponent(bAddCRoom)
                    .addComponent(bAddShow)
                    .addComponent(bAddUser))
                .addGap(18, 18, 18)
                .addGroup(pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListShow)
                    .addComponent(bListMov)
                    .addComponent(bListCRoom)
                    .addComponent(bListUser)
                    .addComponent(bListRes))
                .addGap(18, 18, 18)
                .addGroup(pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDelUser)
                    .addComponent(bDelMov)
                    .addComponent(bDelShow)
                    .addComponent(bDelCRoom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pOptionsLayout.setVerticalGroup(
            pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddMov)
                    .addComponent(bListMov)
                    .addComponent(bDelMov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddCRoom)
                    .addComponent(bListCRoom)
                    .addComponent(bDelCRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddShow)
                    .addComponent(bListShow)
                    .addComponent(bDelShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddUser)
                    .addComponent(bListUser)
                    .addComponent(bDelUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bListRes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pMainLayout = new javax.swing.GroupLayout(pMain);
        pMain.setLayout(pMainLayout);
        pMainLayout.setHorizontalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMainLayout.createSequentialGroup()
                        .addComponent(bLoad)
                        .addGap(18, 18, 18)
                        .addComponent(bSave))
                    .addComponent(pOptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMainLayout.setVerticalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainLayout.createSequentialGroup()
                .addGroup(pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLoad)
                    .addComponent(bSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMain.setBounds(0, 0, 350, 240);
        jLayeredPane1.add(pMain, javax.swing.JLayeredPane.DEFAULT_LAYER);

        liMovieList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(liMovieList);

        bDelMovie.setText("Del Movie");
        bDelMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelMovieActionPerformed(evt);
            }
        });

        bShowMore.setText("Show More");
        bShowMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowMoreActionPerformed(evt);
            }
        });

        tMovieMore.setEditable(false);
        tMovieMore.setColumns(20);
        tMovieMore.setRows(5);
        jScrollPane3.setViewportView(tMovieMore);

        javax.swing.GroupLayout pListMovLayout = new javax.swing.GroupLayout(pListMov);
        pListMov.setLayout(pListMovLayout);
        pListMovLayout.setHorizontalGroup(
            pListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListMovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pListMovLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(pListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bShowMore)
                            .addComponent(bDelMovie))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(pListMovLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pListMovLayout.setVerticalGroup(
            pListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListMovLayout.createSequentialGroup()
                .addGroup(pListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pListMovLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bDelMovie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bShowMore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(pListMovLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pListMov.setBounds(0, 0, 430, 260);
        jLayeredPane1.add(pListMov, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pAddMov.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pAddMov.setMinimumSize(new java.awt.Dimension(600, 400));

        eMovieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMovieNameActionPerformed(evt);
            }
        });

        lMovieName.setText("Movie title:");

        lMovieGenre.setText("Genre:");

        lMovieRating.setText("Rating:");

        lMovieDesc.setText("Descritpion:");

        tMovieDesc.setColumns(20);
        tMovieDesc.setRows(5);
        jScrollPane1.setViewportView(tMovieDesc);

        bAddMovOK.setText("Add Movie");
        bAddMovOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddMovOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAddMovLayout = new javax.swing.GroupLayout(pAddMov);
        pAddMov.setLayout(pAddMovLayout);
        pAddMovLayout.setHorizontalGroup(
            pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddMovLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAddMovOK)
                    .addGroup(pAddMovLayout.createSequentialGroup()
                        .addGroup(pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMovieName)
                            .addComponent(lMovieGenre)
                            .addComponent(lMovieDesc)
                            .addComponent(lMovieRating))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(eMovieName, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(eMovieGenre)
                                .addComponent(eMovieRating)))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        pAddMovLayout.setVerticalGroup(
            pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddMovLayout.createSequentialGroup()
                .addGroup(pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMovieName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMovieGenre)
                    .addComponent(eMovieGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMovieRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMovieRating))
                .addGap(12, 12, 12)
                .addGroup(pAddMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMovieDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAddMovOK)
                .addGap(0, 173, Short.MAX_VALUE))
        );

        pAddMov.setBounds(0, 20, 430, 230);
        jLayeredPane1.add(pAddMov, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bReturn.setText("Return");
        bReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReturnActionPerformed(evt);
            }
        });
        bReturn.setBounds(10, 270, 130, 29);
        jLayeredPane1.add(bReturn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoadActionPerformed
        pOptions.setVisible(true);
        bSave.setVisible(true);
        bReturn.setVisible(true);
        this.mgmt.getData();
    }//GEN-LAST:event_bLoadActionPerformed

    private void eMovieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMovieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMovieNameActionPerformed

    private void bAddMovOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddMovOKActionPerformed
        String name = eMovieName.getText();
        String genre = eMovieGenre.getText();
        String rating = eMovieRating.getText();
        String desc = tMovieDesc.getText();
        mgmt.addMovie(name, genre, rating,desc);
        pMain.setVisible(true);
        pOptions.setVisible(true);
        pAddMov.setVisible(false);
    }//GEN-LAST:event_bAddMovOKActionPerformed

    private void bAddMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddMovActionPerformed
        pOptions.setVisible(false);
        pMain.setVisible(false);
        pAddMov.setVisible(true);
        pAddMov.repaint();
    }//GEN-LAST:event_bAddMovActionPerformed

    private void bListMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListMovActionPerformed
        pMain.setVisible(false);
        pListMov.setVisible(true);
        tMovieMore.setVisible(false);
        String[] movs = new String[mgmt.getMovies().length];
        for(int i = 0;i<mgmt.getMovies().length;i++){
            movs[i] = mgmt.getMovies()[i].getName();
        }
        liMovieList.setListData((String[])movs);
    }//GEN-LAST:event_bListMovActionPerformed

    private void bDelMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelMovieActionPerformed
        int sel = liMovieList.getSelectedIndex();
        if(sel < 0) return;
        mgmt.delMovie(sel);
        pMain.setVisible(true);
        pListMov.setVisible(false);
    }//GEN-LAST:event_bDelMovieActionPerformed

    private void bShowMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowMoreActionPerformed
        int sel = liMovieList.getSelectedIndex();
        if(sel < 0) return;
        tMovieMore.setVisible(true);
        tMovieMore.setText("Name: "+mgmt.getMovies()[sel].getName()+"\nGenre: "+mgmt.getMovies()[sel].getGenre()+"\nRating: "
                +mgmt.getMovies()[sel].getRating()+"\nDesc:\n"+mgmt.getMovies()[sel].getDesc());
    }//GEN-LAST:event_bShowMoreActionPerformed

    private void bReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReturnActionPerformed
        pOptions.setVisible(true);
        pMain.setVisible(true);
        bLoad.setVisible(true);
        bSave.setVisible(true);
        pAddMov.setVisible(false);
        pListMov.setVisible(false);
    }//GEN-LAST:event_bReturnActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        mgmt.saveData();
    }//GEN-LAST:event_bSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddCRoom;
    private javax.swing.JButton bAddMov;
    private javax.swing.JButton bAddMovOK;
    private javax.swing.JButton bAddShow;
    private javax.swing.JButton bAddUser;
    private javax.swing.JButton bDelCRoom;
    private javax.swing.JButton bDelMov;
    private javax.swing.JButton bDelMovie;
    private javax.swing.JButton bDelShow;
    private javax.swing.JButton bDelUser;
    private javax.swing.JButton bListCRoom;
    private javax.swing.JButton bListMov;
    private javax.swing.JButton bListRes;
    private javax.swing.JButton bListShow;
    private javax.swing.JButton bListUser;
    private javax.swing.JButton bLoad;
    private javax.swing.JButton bReturn;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bShowMore;
    private javax.swing.JTextField eMovieGenre;
    private javax.swing.JTextField eMovieName;
    private javax.swing.JTextField eMovieRating;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lCRoomHello;
    private javax.swing.JLabel lCRoomID;
    private javax.swing.JLabel lMovieDesc;
    private javax.swing.JLabel lMovieGenre;
    private javax.swing.JLabel lMovieName;
    private javax.swing.JLabel lMovieRating;
    private javax.swing.JList liMovieList;
    private javax.swing.JPanel pAddCRoom;
    private javax.swing.JPanel pAddMov;
    private javax.swing.JPanel pListMov;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pOptions;
    private javax.swing.JTextArea tMovieDesc;
    private javax.swing.JTextArea tMovieMore;
    // End of variables declaration//GEN-END:variables
}
